"""
Generate comparative results table for all models across all cohorts.
Reads from results/monte_carlo_benchmarks.csv (generated by run_monte_carlo_benchmarks.py).
"""
import os
import pandas as pd
import numpy as np

RESULTS_CSV = "results/monte_carlo_benchmarks.csv"


def load_results():
    if not os.path.exists(RESULTS_CSV):
        print(f"Error: {RESULTS_CSV} not found. Run run_monte_carlo_benchmarks.py first.")
        exit(1)

    df = pd.read_csv(RESULTS_CSV)

    def clean(v):
        return float(str(v).split(' ')[0]) if pd.notna(v) else 0.0

    for col in df.columns:
        if col not in ['Cohort', 'Noise']:
            df[col] = df[col].apply(clean)

    df['Noise_Pct'] = df['Noise'].str.rstrip('%').astype(int)
    return df


def print_table(df):
    cohorts = ['OG China (Primary)', 'West China', 'Japanese']
    noise_levels = [0, 5, 30]

    for cohort in cohorts:
        sub = df[df['Cohort'] == cohort].sort_values('Noise_Pct')
        cols = [c for c in sub.columns if c not in ['Cohort', 'Noise', 'Noise_Pct']]
        col_width = 10

        header = f"  {'Noise':>6} " + " ".join(f"{c:>{col_width}}" for c in cols)
        sep = f"  {'─'*6} " + " ".join(f"{'─'*col_width}" for c in cols)
        print(f"\n  {'='*80}")
        print(f"  {cohort}")
        print(f"  {'='*80}")
        print(header)
        print(sep)

        for nl in noise_levels:
            row = sub[sub['Noise_Pct'] == nl]
            if len(row) == 0: continue
            vals = [f"{row[c].values[0]:{col_width}.4f}" for c in cols]
            print(f"  {nl:>4}%  " + " ".join(vals))

        r0 = sub[sub['Noise_Pct'] == 0]
        r30 = sub[sub['Noise_Pct'] == 30]
        if len(r0) and len(r30):
            deltas = [f"{r30[c].values[0]-r0[c].values[0]:+{col_width}.4f}" for c in cols]
            print(f"  {'Δ':>6}  " + " ".join(deltas))

    # Summary: best per cohort
    print(f"\n  {'='*80}")
    print("  BEST MODEL PER COHORT")
    print(f"  {'='*80}")
    for cohort in cohorts:
        sub = df[df['Cohort'] == cohort]
        sub0 = sub[sub['Noise_Pct'] == 0]
        cols = [c for c in sub0.columns if c not in ['Cohort', 'Noise', 'Noise_Pct']]
        best_col = max(cols, key=lambda c: sub0[c].values[0])
        print(f"  {cohort:<30} {best_col}  ({sub0[best_col].values[0]:.4f})")

    # Overfitting summary
    print(f"\n  {'='*80}")
    print("  OVERFITTING (Internal 0% - External 0%)")
    print(f"  {'='*80}")
    int_0 = df[(df['Cohort'] == 'OG China (Primary)') & (df['Noise_Pct'] == 0)]
    ext_0 = df[(df['Cohort'] == 'West China') & (df['Noise_Pct'] == 0)]
    print(f"  {'Model':<25} {'Internal':>10} {'West China':>12} {'Overfit Δ':>10}")
    print(f"  {'─'*25} {'─'*10} {'─'*12} {'─'*10}")
    for c in cols:
        i_val = int_0[c].values[0]
        e_val = ext_0[c].values[0]
        print(f"  {c:<25} {i_val:>10.4f} {e_val:>12.4f} {i_val-e_val:>+10.4f}")

    # Noise degradation summary
    print(f"\n  {'='*80}")
    print("  NOISE DEGRADATION (West China, 0% → 30%)")
    print(f"  {'='*80}")
    w0 = df[(df['Cohort'] == 'West China') & (df['Noise_Pct'] == 0)]
    w30 = df[(df['Cohort'] == 'West China') & (df['Noise_Pct'] == 30)]
    print(f"  {'Model':<25} {'0%':>8} {'30%':>8} {'Δ':>10}")
    print(f"  {'─'*25} {'─'*8} {'─'*8} {'─'*10}")
    for c in cols:
        v0 = w0[c].values[0]; v30 = w30[c].values[0]
        print(f"  {c:<25} {v0:>8.4f} {v30:>8.4f} {v30-v0:>+10.4f}")


def main():
    df = load_results()
    print_table()


if __name__ == "__main__":
    main()
